---
resources:
- name: pu-git
  type: git
  source:
    uri: https://github.com/RyanDur/in-memory-test-db
    branch: master

- name: p-and-u-api-dev
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{username}}
    password: {{password}}
    organization: {{org}}
    space: {{space}}

jobs:
- name: test
  public: true
  plan:
  - get: pu-git
    trigger: true
  - task: hello-unicorn
    file: pu-git/ci/tasks/build.yml

- name: deploy-dev
  serial: true
  plan:
  - get: pu-git
    trigger: true
    passed: [test]
  - put: p-and-u-api-dev
    params:
      manifest: pu-git/p-and-u-api/manifest.yaml