---
resources:
- name: pu-git
  type: git
  source:
    uri: https://github.com/RyanDur/in-memory-test-db
    branch: master

- name: staging-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: RyanDur
    password: 12Durken!
    organization: ConcoursePrac
    space: Pumpkin-Butt

jobs:
- name: job-hello-unicorn
  public: true
  plan:
  - get: pu-git
    trigger: true
  - task: hello-unicorn
    file: pu-git/ci/build.yml
  - put: staging-app
    

