---
resources:
- name: pu-rc
  type: s3
  source:
    bucket: pu-rc-artifacts
    regexp: p-and-u-api-(.*).jar
    endpoint: http://10.35.102.154:9000
    access_key_id: {{s3-key-id}}
    secret_access_key: {{s3-access-key}}

- name: pu-git
  type: git
  source:
    uri: https://github.com/RyanDur/in-memory-test-db
    branch: master

- name: pu-pcf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{username}}
    password: {{password}}
    organization: {{org}}
    space: {{space}}

jobs:
- name: build
  public: true
  plan:
  - get: pu-git
    trigger: true
  - task: test & build
    file: pu-git/ci/tasks/build.yml
  - put: pu-rc
    params:
      file: pu-jars/p-and-u-api-*.jar

- name: deploy-pcf
  serial: true
  plan:
  - get: pu-rc
    trigger: true
    passed: [build]
  - get: pu-git
  - put: pu-pcf
    params:
      manifest: pu-git/p-and-u-api/manifest.yaml