---
resources:
- name: pu-git
  type: git
  source:
    uri: https://github.com/RyanDur/in-memory-test-db
    branch: master

- name: pu-pcf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{username}}
    password: {{password}}
    organization: {{org}}
    space: {{space}}

jobs:
- name: run-tests
  public: true
  plan:
  - get: pu-git
    trigger: true
  - task: hello-unicorn
    file: pu-git/ci/tasks/test.yml

- name: deploy-pcf
  serial: true
  plan:
  - get: pu-git
    trigger: true
    passed: [run-tests]
  - put: pu-pcf
    params:
      manifest: pu-git/p-and-u-api/manifest.yaml